spring:
  application:
    name: recruitment_test

  main:
    allow-bean-definition-overriding: true

  threads:
    virtual:
      enabled: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          bands:
            url: ${BANDS_URL}